[project]
name = "hike"
version = "0.1.0"
description = ""
authors = [{ name = "Joao Silva", email = "joaosggtl@gmail.com" }]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.backends._legacy:_Backend"
